### ISSUE TITLE
Improve test-library workflow 

### ISSUE THREAD

**Issue by mesejo** [letsql/letsql#224]
After these PRs: https://github.com/letsql/letsql/pull/216 and https://github.com/letsql/letsql/pull/223 are solved

Add test of the complete examples folder:

```yaml      
       - name: Poetry install
        run: poetry install --extras="examples"
        working-directory: ${{ github.workspace }}

      - name: maturin develop
        run: poetry run maturin develop --release
        working-directory: ${{ github.workspace }}

      - name: poetry pytest
        run: poetry run pytest --import-mode=importlib python/letsql/tests/test_examples.py -v
        working-directory: ${{ github.workspace }}
```
